# Generated by Django 2.2.24 on 2021-11-14 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarAtencion',
            fields=[
                ('idLugarAtencion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, verbose_name='Lugar de atencion')),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='FechaIngreso',
        ),
        migrations.AddField(
            model_name='paciente',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='lugarAtencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paciente.LugarAtencion'),
            preserve_default=False,
        ),
    ]
