# Generated by Django 2.2.24 on 2021-11-29 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0002_historial_lugaratencion_medico_paciente_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='idusuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
