# Generated by Django 2.2.24 on 2021-11-14 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20211114_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombres del Médico')),
                ('snombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre del Médico')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido del Médico')),
                ('sapellido', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo Apellido del Médico')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion del Médico')),
                ('especialidad', models.CharField(max_length=200, verbose_name='Especialidad del Médico')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombreMedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Medico'),
        ),
    ]
