# Generated by Django 3.2.4 on 2021-11-14 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20211114_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombreMedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.medico', verbose_name='Nombre Médico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
