# Generated by Django 3.2.4 on 2021-11-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20211114_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
    ]
