# Generated by Django 2.2.24 on 2021-11-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20211128_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={},
        ),
        migrations.AlterModelManagers(
            name='medico',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='medico',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
