# Generated by Django 2.2.24 on 2021-11-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20211114_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='id_historial',
            field=models.IntegerField(default=999, verbose_name='Numero de historial'),
        ),
    ]
