# Generated by Django 2.2.24 on 2021-11-20 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_paciente_id_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idhistorial', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero historial')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idregistro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de registro')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('tipoAtencion', models.CharField(max_length=200, verbose_name='Tipo de Atencion')),
                ('Servicio', models.CharField(max_length=200, verbose_name='Servicio')),
                ('Diagnostico', models.CharField(max_length=200, verbose_name='Diagnostico')),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Historial'),
        ),
        migrations.AddField(
            model_name='historial',
            name='idregistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Registro'),
        ),
    ]
