# Generated by Django 2.2.24 on 2021-12-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20211129_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateTimeField(default='2000-01-01', verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
    ]
