# Generated by Django 2.2.24 on 2021-12-04 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='idregistro',
        ),
        migrations.AddField(
            model_name='historial',
            name='diagnostico',
            field=models.CharField(max_length=150, null=True, verbose_name='Diagnostico'),
        ),
        migrations.AddField(
            model_name='historial',
            name='diagnostico_admision',
            field=models.CharField(max_length=150, null=True, verbose_name='Diagnostico de admision'),
        ),
        migrations.AddField(
            model_name='historial',
            name='diagnostico_clinico_final',
            field=models.CharField(max_length=200, null=True, verbose_name='Diagnostico clinico final'),
        ),
        migrations.AddField(
            model_name='historial',
            name='enfermedad_actual',
            field=models.CharField(max_length=150, null=True, verbose_name='Enfermedad actual'),
        ),
        migrations.AddField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='historial',
            name='fecha_alta_clinica',
            field=models.DateTimeField(null=True, verbose_name='Fecha alta clinica'),
        ),
        migrations.AddField(
            model_name='historial',
            name='fecha_alta_medica',
            field=models.DateTimeField(null=True, verbose_name='Fecha alta Medica'),
        ),
        migrations.AddField(
            model_name='historial',
            name='motivo_ingreso',
            field=models.CharField(max_length=150, null=True, verbose_name='Motivo de ingreso'),
        ),
        migrations.AddField(
            model_name='historial',
            name='servicio',
            field=models.CharField(max_length=30, null=True, verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='historial',
            name='tipo_atencion',
            field=models.CharField(max_length=50, null=True, verbose_name='Tipo de atencion'),
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_signosvitales', models.AutoField(primary_key=True, serialize=False, verbose_name='id signos vitales')),
                ('respiracion', models.CharField(max_length=50, null=True, verbose_name='Respiracion')),
                ('tension', models.CharField(max_length=50, null=True, verbose_name='Tension')),
                ('evaluacion', models.CharField(max_length=150, null=True, verbose_name='Evaluacion')),
                ('miccion', models.CharField(max_length=150, null=True, verbose_name='Miccion')),
                ('vomito', models.CharField(max_length=150, null=True, verbose_name='Vomito')),
                ('gases', models.CharField(max_length=50, null=True, verbose_name='Gases')),
                ('dolor', models.CharField(max_length=50, null=True, verbose_name='Dolor')),
                ('transfusion_sangre', models.CharField(max_length=100, null=True, verbose_name='Transfusion de Sangre')),
                ('frecuencia_cardiaca', models.CharField(max_length=50, null=True, verbose_name='Frecuencia Cardiaca')),
                ('saturacion', models.CharField(max_length=50, null=True, verbose_name='Saturacion')),
                ('presion_venosa_central', models.CharField(max_length=50, null=True, verbose_name='Presión Venosa Central')),
                ('presion_arterial_media', models.CharField(max_length=50, null=True, verbose_name='Presión Arterial Media')),
                ('peso', models.CharField(max_length=50, null=True, verbose_name='Peso')),
                ('talla', models.CharField(max_length=50, null=True, verbose_name='Talla')),
                ('Presion_Intracraneal', models.CharField(max_length=50, null=True, verbose_name='Temperatura')),
                ('Presion_arterial_pulmonar', models.CharField(max_length=50, null=True, verbose_name='Temperatura')),
                ('observaciones', models.CharField(max_length=50, null=True, verbose_name='Observaciones')),
                ('temperatura', models.CharField(max_length=50, null=True, verbose_name='Temperatura')),
                ('paciente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='evaluacion',
            fields=[
                ('idevaluacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id evaluacion')),
                ('fecha_evaluacion', models.DateTimeField(verbose_name='Fecha de evaluacion')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
