# Generated by Django 2.2.24 on 2021-12-04 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_auto_20211203_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha registro'),
        ),
    ]
