# Generated by Django 2.2.24 on 2021-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_signosvitales_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='Presion_Intracraneal',
            field=models.CharField(max_length=50, null=True, verbose_name='Presion Intracraneal'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='Presion_arterial_pulmonar',
            field=models.CharField(max_length=50, null=True, verbose_name='Presion Arterial Pulmonar'),
        ),
    ]
