# Generated by Django 2.2.24 on 2021-12-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_auto_20211204_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombreMedicoAdmin',
            field=models.CharField(default='cuidador', max_length=45, verbose_name='Nombre Medico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombreMedico',
            field=models.CharField(default='cuidador', max_length=45, verbose_name='Nombre Medico'),
        ),
    ]
