# Generated by Django 2.2.24 on 2021-12-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_auto_20211205_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='n_historial',
        ),
    ]
