# Generated by Django 2.2.24 on 2021-12-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_remove_paciente_n_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='diagnostico_admision',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diagnostico de admision'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='diagnostico_clinico_final',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Diagnostico clinico final'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='enfermedad_actual',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Enfermedad actual'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_alta_clinica',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha alta clinica'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_alta_medica',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha alta Medica'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='motivo_ingreso',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo de ingreso'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='servicio',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tipo_atencion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de atencion'),
        ),
    ]
