# Generated by Django 2.2.24 on 2021-12-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0015_auto_20211207_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='tipo_atencion',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='paciente.LugarAtencion'),
            preserve_default=False,
        ),
    ]
